# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t virtual-music-system .
            #echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            #docker push xiaomi388/$IMAGE_NAME:$TAG
            docker run virtual-music-system ./docker_test.sh
