# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t virtual-music-system .
            docker save -o /image.tar virtual-music-system
      - persist_to_workspace:
          root: /
          paths:
            - image.tar
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /
      - run:
          name: Run Tests
          command: |
            docker load -i image.tar
            docker run virtual-music-system ./docker_test.sh
  publish:
    docker:
      - image: cimg/base:2021.04
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /
      - run:
          name: Publish
          command: |
            docker load -i image.tar
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            TARGET=xiaomi388/virtual-music-system:`git describe --tags`
            docker tag virtual-music-system $TARGET
            docker push $TARGET

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
      - publish:
          requires:
            - test
          filters:
            tags: 
              only:
                /.*/





      



