# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: xiaomi388/virtual-music-system-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Tests
          command: ./scripts/docker_test.sh
  publish:
    docker:
      - image: circli-ci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish
          command: |
            VERSION=`git describe --exact-match --tags $(git log -n1 --pretty='%h') 2>/dev/null` || true
            [ -z "$VERSION" ] && exit 0
            docker build -t xiaomi388/virtual-music-system .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            TARGET=xiaomi388/virtual-music-system:$VERSION
            docker tag virtual-music-system $TARGET
            docker push $TARGET
            TARGET=xiaomi388/virtual-music-system:latest
            docker tag virtual-music-system $TARGET
            docker push $TARGET
workflows:
  main:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - publish:
          filters:
            tags:
              only: /.*/
          
