# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from xiaomi388/virtual-music-system -t virtual-music-system .        
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Run Tests
          command: |
            docker run virtual-music-system ./docker_test.sh
  publish:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Publish
          command: |
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push xiaomi388/virtual-music-system:`git describe --tags`

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires: 
            - build
      - publish:
          requires:
            - test
          filters:
            tags: 
              only:
                /.*/





      



