http:
  hostport: "0.0.0.0:10234"

metadata:
  driver:
    netease:
      baseurl: "http://neapi.n.xiaomi388.com:10444"

song:
  localrepo:
    file:
      rootdir: "/tmp/filerepo"
  remoterepo:
    youtube: ""
